// <auto-generated />
using System;
using Holerite.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holerite.Infra.Migrations
{
    [DbContext(typeof(HoleriteContext))]
    partial class HoleriteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Holerite.Core.Models.Arquivos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Arquivo")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EmailEnviado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PessoasId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PessoasId");

                    b.ToTable("Arquivos", (string)null);
                });

            modelBuilder.Entity("Holerite.Core.Models.Empresas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("Holerite.Core.Models.Pessoas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpresasId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProfissaoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProfissoesId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresasId");

                    b.HasIndex("ProfissoesId");

                    b.ToTable("Pessoas", (string)null);
                });

            modelBuilder.Entity("Holerite.Core.Models.Profissoes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProfissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profissoes", (string)null);
                });

            modelBuilder.Entity("Holerite.Core.Models.Arquivos", b =>
                {
                    b.HasOne("Holerite.Core.Models.Pessoas", "Pessoas")
                        .WithMany()
                        .HasForeignKey("PessoasId");

                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("Holerite.Core.Models.Pessoas", b =>
                {
                    b.HasOne("Holerite.Core.Models.Empresas", "Empresas")
                        .WithMany()
                        .HasForeignKey("EmpresasId");

                    b.HasOne("Holerite.Core.Models.Profissoes", "Profissoes")
                        .WithMany()
                        .HasForeignKey("ProfissoesId");

                    b.Navigation("Empresas");

                    b.Navigation("Profissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
